remote_theme: jekyll/minima

plugins:
  - jekyll-remote-theme

minima:
  skin: auto

title: Hidden depths in simple things

author: inesvar

description: I like coding in Rust, and math (geometry especially).